// File generated by generic script using configuration from google-services.json and GoogleService-Info.plist
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by manually adding web options.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6gi_QKb398OgyqB9pTtLVvltijJVppBg',
    appId: '1:265361809546:android:c0f797f7f8e5a53fb60d73',
    messagingSenderId: '265361809546',
    projectId: 'premium-force',
    storageBucket: 'premium-force.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP7Kf8cocyotfnWNAP82eZX-xvOIwnHPs',
    appId: '1:265361809546:ios:8e8a985940fa81d6b60d73',
    messagingSenderId: '265361809546',
    projectId: 'premium-force',
    storageBucket: 'premium-force.firebasestorage.app',
    iosBundleId: 'com.brandbik.premiumforce',
  );
}
