// File generated by generic script using configuration from google-services.json and GoogleService-Info.plist
//
// These are the `com.brandbik.premiumforcedriver` apps. The Firebase project
// `premium-force` also holds a `com.brandbik.premiumforce` app per platform,
// and an earlier revision of this file pointed at those: pushes and crash
// reports from this build landed on the wrong app. Both share the project's
// `projectId` and `databaseURL`, so the database kept working and hid it.
// The values below must stay in step with android/app/google-services.json
// and ios/Runner/GoogleService-Info.plist.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by manually adding web options.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6gi_QKb398OgyqB9pTtLVvltijJVppBg',
    appId: '1:265361809546:android:ab756b107b2c6c84b60d73',
    messagingSenderId: '265361809546',
    projectId: 'premium-force',
    storageBucket: 'premium-force.firebasestorage.app',
    databaseURL: 'https://premium-force-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDpclMt3ueQIrr4-DEu-dImey6fcoUfVI',
    appId: '1:265361809546:ios:38d5b09c1f24947ab60d73',
    messagingSenderId: '265361809546',
    projectId: 'premium-force',
    storageBucket: 'premium-force.firebasestorage.app',
    databaseURL: 'https://premium-force-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosBundleId: 'com.brandbik.premiumforcedriver',
  );
}
